---

- name: Кейс НОРСИ-ТРАНС ЗАДАЧА 1
  hosts: all
  become: true

  tasks:

  - name: В каталоге /etc ищем файлы измененые за последние 5 часов
    shell:
      cmd: find /etc/ -mmin -300 -type f
    register: result_of_scan

  - name: Собираем логи и пакуем в файлы

    shell:
      chdir: /home/user01/
      cmd: "{{item}}"
    loop:
      - c_time=$(date +"%s")
      - t_time=$(($c_date - 18000))
      - journalctl -ex -S "$(date -d "-5 hours" +"%Y-%m-%d %T")" -U "$(date +"%Y-%m-%d %T")" | grep user01  | grep COMMAND | tee u_file
      - echo $(find /etc/ -mmin -300 -type f) | tee c_file
    register: result_of_shell
    when: result_of_scan.stdout != ""

  - name: Копируем файлы на машину администратора

    fetch:
      src: /home/user01/c_file
      dest: /home/user01/cheking/{{ansible_hostname}}/c_file
      flat: yes

  - name:

    fetch:
      src: /home/user01/u_file
      dest: /home/user01/cheking/{{ansible_hostname}}/u_file
      flat: yes

    when: result_of_shell is not skipped

  - name: Чистим за собой

    file:
      path: /home/user01/{{item}}
      state: absent
    loop:
      - c_file
      - u_file