'''
Алгоритм решения в следующем:

1. Сканируем каталог /etc на всех серверах и ищем файлы измененные за последние 5 часов
2. Если изменения есть - создаем в директории пользователя user01 каталог 4_check
   2.1 сохраняем вывод в файл c_file
   2.2 собираем в файл u_file с логов аудита всё что делал указанный пользователь за последние 5 часов
   2.3 Скидываем оба файла себе на машину
   2.4 Чистим за собой 
   
'''

---
- name: Кейс НОРСИ-ТРАНС ЗАДАЧА 1
  hosts: all
  #включаем выполнение плейбука с sudo привилегиями пользователя
  become: true

  tasks:

      '''Используем модуль ansible.builtin.shell для кроссплатформенности'''
    - name: В каталоге /etc ищем файлы измененые за последние 5 часов
      shell:
        cdir: /home/user01/
        cmd: find /etc -mmin -300
      register: result

    - name: Out
      debug:
        var: result